apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitor-namespaces-acc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: monitor-namespaces
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: network-policy-operator
rules:
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["*"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageaccounts"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitor-namespaces
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: monitor-namespaces
subjects:
- kind: ServiceAccount
  name: monitor-namespaces-acc
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: network-policy-operator-binding
subjects:
- kind: ServiceAccount
  name: monitor-namespaces-acc
  namespace: default
roleRef:
  kind: ClusterRole
  name: network-policy-operator
  apiGroup: rbac.authorization.k8s.io
